name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: self-hosted
    services:
      docker:
        image: docker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo apt-get install -y openssh-client bash

      - name: Build Docker Image
        run: docker-compose -f ${{ secrets.DOCKER_COMPOSE_PATH }} build

      - name: Rename Tag Docker Image
        run: docker tag ${{ secrets.DOCKER_IMAGE_BUILD_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:latest

      - name: Print Current Working Directory
        run: pwd

      - name: Save and Upload Docker Image
        run: |
          pwd
          docker save -o docker_image.tar ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:latest
          sudo chmod 777 docker_image.tar
          
      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker_image
          path: docker_image.tar

      - name: Clean Up Docker Image File
        run: rm -f docker_image.tar

  push:
    needs: build
    name: Push Docker Image to Docker Hub
    runs-on: self-hosted
    services:
      docker:
        image: docker:latest
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker_image

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load Docker Image
        run: docker load -i docker_image.tar

      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with: 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKER_REPO_NAME}}:latest

  deploy:
    needs: push
    name: Deploy to VPS
    runs-on: self-hosted
    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'echo "SSH connection successful"'

      - name: Deploy via SSH
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'sudo su - ${{ secrets.VPS_USER }} ${{ secrets.DEPLOY_SCRIPTS_PATH }}'
